# POS Printer Agent - Windows Config

# Servidor WebSocket de production (Cloudflare SSL)
#server.url=wss://api.lapasadita.app/ws/printer
server.url=ws://localhost:8080/ws/printer

# Unique identifier for this POS station
station.id=POS1

# Printer Windows
#printer.name=EPSON TM-T88V Receipt5
printer.path=/dev/usb/lp6

# Business
business.name=LA PASADITA
business.address=Morelos #124 Col. Centro C.P. 46400
business.phone=374 104 3536

# Scale
#scale.port=COM3
scale.port=/dev/ttyACM0
scale.enabled=false
scale.autoConnect=true
